source 'https://rubygems.org'

gem 'rails', '4.2.6'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# These gem versions are what is available as apt packages in Ubuntu 16.04
gem 'sqlite3', '1.3.11'
gem 'json', '1.8.3'
gem 'nokogiri', '1.12.5'
